<?php
/**
 * Created by Magenest.
 * Author: Pham Quang Hau
 * Date: 30/05/2016
 * Time: 21:46
 */
// @codingStandardsIgnoreFile
/** @var \Magenest\StripePayment\Block\Adminhtml\Order\View\Info\Charge $block */
$dataView = $block->getDataView();;
?>

<table class="data-table admin__table-secondary">
    <tbody>

    <?php foreach ($dataView as $row) { ?>
        <tr>
            <td><?=@$row['label']?></td>
            <td><?=@$row['value']?></td>
        </tr>
    <?php } ?>
    </tbody>
</table>
