#! /bin/bash
rm ./app/code/Wyomind/SimpleGoogleShopping/view/adminhtml/layout/simplegoogleshopping_feeds_showreport.xml
rm ./app/code/Wyomind/SimpleGoogleShopping/view/adminhtml/layout/simplegoogleshopping_feeds_preview.xml
rm ./app/code/Wyomind/SimpleGoogleShopping/view/adminhtml/layout/simplegoogleshopping_feeds_index.xml
rm ./app/code/Wyomind/SimpleGoogleShopping/view/adminhtml/layout/simplegoogleshopping_feeds_edit.xml
rm ./app/code/Wyomind/SimpleGoogleShopping/view/adminhtml/layout/simplegoogleshopping_feeds_new.xml
rm ./app/code/Wyomind/SimpleGoogleShopping/view/adminhtml/templates/edit/configuration.phtml
rm ./app/code/Wyomind/SimpleGoogleShopping/Block/Adminhtml/Feeds/Edit/Tab/Configuration.php
rm ./app/code/Wyomind/SimpleGoogleShopping/view/adminhtml/templates/edit/categories.phtml
rm ./app/code/Wyomind/SimpleGoogleShopping/Model/ResourceModel/Product/Collection_2.1.php
rm ./app/code/Wyomind/SimpleGoogleShopping/view/adminhtml/templates/edit/translate.phtml
rm ./app/code/Wyomind/SimpleGoogleShopping/Block/Adminhtml/Feeds/Edit/Tab/Categories.php
rm ./app/code/Wyomind/Core/view/frontend/layout/licensemanager_activation_webservice.xml
rm ./app/code/Wyomind/SimpleGoogleShopping/view/adminhtml/templates/edit/utils.js.phtml
rm ./app/code/Wyomind/SimpleGoogleShopping/view/adminhtml/web/js/feeds/configuration.js
rm ./app/code/Wyomind/SimpleGoogleShopping/view/adminhtml/templates/edit/blackbox.phtml
rm ./app/code/Wyomind/SimpleGoogleShopping/Controller/Adminhtml/Feeds/Librarysample.php
rm ./app/code/Wyomind/SimpleGoogleShopping/Model/ResourceModel/Functions/Collection.php
rm ./app/code/Wyomind/SimpleGoogleShopping/view/adminhtml/templates/edit/filters.phtml
rm ./app/code/Wyomind/SimpleGoogleShopping/Controller/Adminhtml/Feeds/Samplereport.php
rm ./app/code/Wyomind/SimpleGoogleShopping/view/adminhtml/web/images/loader-bg-top.gif
rm ./app/code/Wyomind/Core/Block/Adminhtml/System/Config/Form/Field/ActivationFlag.php
rm ./app/code/Wyomind/SimpleGoogleShopping/data/Google/Taxonomies/[default] en_US.txt
rm ./app/code/Wyomind/SimpleGoogleShopping/Model/ResourceModel/Product/Collection.php
rm ./app/code/Wyomind/SimpleGoogleShopping/Block/Adminhtml/Feeds/Edit/Tab/Filters.php
rm ./app/code/Wyomind/SimpleGoogleShopping/Controller/Adminhtml/Feeds/Showreport.php
rm ./app/code/Wyomind/SimpleGoogleShopping/view/adminhtml/web/js/feeds/categories.js
rm ./app/code/Wyomind/Core/view/adminhtml/web/js/codemirror/javascript/javascript.js
rm ./app/code/Wyomind/SimpleGoogleShopping/Controller/Adminhtml/Feeds/Categories.php
rm ./app/code/Wyomind/SimpleGoogleShopping/Block/Adminhtml/Feeds/Renderer/Action.php
rm ./app/code/Wyomind/SimpleGoogleShopping/Block/Adminhtml/Feeds/Renderer/Status.php
rm ./app/code/Wyomind/SimpleGoogleShopping/Controller/Adminhtml/Feeds/NewAction.php
rm ./app/code/Wyomind/SimpleGoogleShopping/Model/ResourceModel/Feeds/Collection.php
rm ./app/code/Wyomind/SimpleGoogleShopping/view/adminhtml/web/css/configuration.css
rm ./app/code/Wyomind/SimpleGoogleShopping/Model/ResourceModel/Store/Collection.php
rm ./app/code/Wyomind/SimpleGoogleShopping/view/adminhtml/templates/edit/cron.phtml
rm ./app/code/Wyomind/SimpleGoogleShopping/view/adminhtml/web/js/feeds/blackbox.js
rm ./app/code/Wyomind/Core/view/adminhtml/web/js/codemirror/htmlmixed/htmlmixed.js
rm ./app/code/Wyomind/Core/view/adminhtml/web/js/codemirror/multiplex/multiplex.js
rm ./app/code/Wyomind/SimpleGoogleShopping/Block/Adminhtml/Feeds/Edit/Tab/Cron.php
rm ./app/code/Wyomind/SimpleGoogleShopping/Controller/Adminhtml/Feeds/Generate.php
rm ./app/code/Wyomind/SimpleGoogleShopping/Block/Adminhtml/Feeds/Renderer/Link.php
rm ./app/code/Wyomind/SimpleGoogleShopping/Controller/Adminhtml/Feeds/Preview.php
rm ./app/code/Wyomind/SimpleGoogleShopping/view/adminhtml/web/js/feeds/filters.js
rm ./app/code/Wyomind/SimpleGoogleShopping/view/adminhtml/templates/preview.phtml
rm ./app/code/Wyomind/Core/Block/Adminhtml/System/Config/Form/Field/Encrypted.php
rm ./app/code/Wyomind/Core/view/adminhtml/layout/adminhtml_system_config_edit.xml
rm ./app/code/Wyomind/SimpleGoogleShopping/Helper/AttributesStockInTheChannel.php
rm ./app/code/Wyomind/SimpleGoogleShopping/Controller/Adminhtml/Feeds/Updater.php
rm ./app/code/Wyomind/SimpleGoogleShopping/Controller/Adminhtml/Feeds/Library.php
rm ./app/code/Wyomind/SimpleGoogleShopping/view/adminhtml/web/css/categories.css
rm ./app/code/Wyomind/SimpleGoogleShopping/view/adminhtml/email/cron_report.html
rm ./app/code/Wyomind/SimpleGoogleShopping/Controller/Adminhtml/Feeds/Delete.php
rm ./app/code/Wyomind/SimpleGoogleShopping/Controller/Adminhtml/Feeds/Sample.php
rm ./app/code/Wyomind/SimpleGoogleShopping/view/adminhtml/web/js/feeds/index.js
rm ./app/code/Wyomind/SimpleGoogleShopping/Controller/Adminhtml/Feeds/Index.php
rm ./app/code/Wyomind/SimpleGoogleShopping/view/adminhtml/web/images/resize.png
rm ./app/code/Wyomind/SimpleGoogleShopping/view/adminhtml/web/images/loader.gif
rm ./app/code/Wyomind/SimpleGoogleShopping/view/adminhtml/templates/empty.phtml
rm ./app/code/Wyomind/SimpleGoogleShopping/view/adminhtml/templates/index.phtml
rm ./app/code/Wyomind/SimpleGoogleShopping/view/adminhtml/web/js/feeds/cron.js
rm ./app/code/Wyomind/SimpleGoogleShopping/Controller/Adminhtml/Feeds/Edit.php
rm ./app/code/Wyomind/SimpleGoogleShopping/view/adminhtml/web/css/blackbox.css
rm ./app/code/Wyomind/SimpleGoogleShopping/Controller/Adminhtml/Feeds/Save.php
rm ./app/code/Wyomind/SimpleGoogleShopping/Block/Adminhtml/Feeds/Edit/Tabs.php
rm ./app/code/Wyomind/SimpleGoogleShopping/Block/Adminhtml/Feeds/Edit/Form.php
rm ./app/code/Wyomind/SimpleGoogleShopping/view/adminhtml/web/css/filters.css
rm ./app/code/Wyomind/SimpleGoogleShopping/view/adminhtml/web/css/preview.css
rmdir  ./app/code/Wyomind/SimpleGoogleShopping/Block/Adminhtml/Feeds/Renderer
rm ./app/code/Wyomind/SimpleGoogleShopping/view/adminhtml/requirejs-config.js
rmdir  ./app/code/Wyomind/SimpleGoogleShopping/Block/Adminhtml/Feeds/Edit/Tab
rm ./app/code/Wyomind/SimpleGoogleShopping/Model/ResourceModel/Functions.php
rm ./app/code/Wyomind/SimpleGoogleShopping/Block/Adminhtml/Category/Tree.php
rmdir  ./app/code/Wyomind/SimpleGoogleShopping/Model/ResourceModel/Functions
rm ./app/code/Wyomind/SimpleGoogleShopping/Block/Adminhtml/Feeds/Preview.php
rmdir  ./app/code/Wyomind/SimpleGoogleShopping/view/adminhtml/templates/edit
rm ./app/code/Wyomind/Core/view/adminhtml/web/js/codemirror/matchbrackets.js
rm ./app/code/Wyomind/SimpleGoogleShopping/data/Google/Taxonomies/nl_NL.txt
rm ./app/code/Wyomind/SimpleGoogleShopping/Model/ResourceModel/TaxClass.php
rm ./app/code/Wyomind/SimpleGoogleShopping/data/Google/Taxonomies/en_AU.txt
rm ./app/code/Wyomind/SimpleGoogleShopping/data/Google/Taxonomies/fr_FR.txt
rm ./app/code/Wyomind/SimpleGoogleShopping/data/Google/Taxonomies/it_IT.txt
rm ./app/code/Wyomind/SimpleGoogleShopping/Block/Adminhtml/Feeds/Report.php
rm ./app/code/Wyomind/SimpleGoogleShopping/data/Google/Taxonomies/de_DE.txt
rm ./app/code/Wyomind/SimpleGoogleShopping/data/Google/Taxonomies/en_GB.txt
rm ./app/code/Wyomind/SimpleGoogleShopping/data/Google/Taxonomies/es_ES.txt
rm ./app/code/Wyomind/SimpleGoogleShopping/view/adminhtml/web/images/d.png
rmdir  ./app/code/Wyomind/Core/view/adminhtml/web/js/codemirror/javascript
rm ./app/code/Wyomind/SimpleGoogleShopping/view/adminhtml/web/css/cron.css
rm ./app/code/Wyomind/SimpleGoogleShopping/Helper/AttributesCategories.php
rm ./app/code/Wyomind/SimpleGoogleShopping/Helper/SimpleGoogleShopping.php
rm ./app/code/Wyomind/Core/view/adminhtml/web/js/codemirror/autorefresh.js
rm ./app/code/Wyomind/Core/view/adminhtml/web/js/codemirror/active-line.js
rm ./app/code/Wyomind/Core/view/adminhtml/web/js/codemirror/clike/clike.js
rmdir  ./app/code/Wyomind/SimpleGoogleShopping/view/adminhtml/web/js/feeds
rm ./app/code/Wyomind/Core/view/adminhtml/web/js/codemirror/codemirror.css
rmdir  ./app/code/Wyomind/SimpleGoogleShopping/Model/ResourceModel/Product
rmdir  ./app/code/Wyomind/Core/view/adminhtml/web/js/codemirror/multiplex
rmdir  ./app/code/Wyomind/SimpleGoogleShopping/Block/Adminhtml/Feeds/Edit
rm ./app/code/Wyomind/Core/view/adminhtml/web/js/codemirror/codemirror.js
rmdir  ./app/code/Wyomind/Core/view/adminhtml/web/js/codemirror/htmlmixed
rm ./app/code/Wyomind/Core/view/adminhtml/web/js/codemirror/formatting.js
rm ./app/code/Wyomind/Core/view/adminhtml/web/js/codemirror/fullscreen.js
rm ./app/code/Wyomind/SimpleGoogleShopping/Block/Adminhtml/Feeds/Edit.php
rm ./app/code/Wyomind/SimpleGoogleShopping/Helper/AttributesInventory.php
rm ./app/code/Wyomind/SimpleGoogleShopping/Model/ResourceModel/Images.php
rm ./app/code/Wyomind/SimpleGoogleShopping/Block/Adminhtml/Feeds/Grid.php
rm ./app/code/Wyomind/SimpleGoogleShopping/Controller/Adminhtml/Feeds.php
rmdir  ./app/code/Wyomind/SimpleGoogleShopping/Controller/Adminhtml/Feeds
rmdir  ./app/code/Wyomind/SimpleGoogleShopping/view/adminhtml/web/images
rm ./app/code/Wyomind/Core/view/adminhtml/web/js/codemirror/mdn-like.css
rmdir  ./app/code/Wyomind/SimpleGoogleShopping/Model/ResourceModel/Store
rm ./app/code/Wyomind/SimpleGoogleShopping/Controller/Feeds/Generate.php
rm ./app/code/Wyomind/SimpleGoogleShopping/Model/ResourceModel/Feeds.php
rmdir  ./app/code/Wyomind/SimpleGoogleShopping/Model/ResourceModel/Feeds
rm ./app/code/Wyomind/SimpleGoogleShopping/Console/Command/Generate.php
rmdir  ./app/code/Wyomind/SimpleGoogleShopping/view/adminhtml/templates
rmdir  ./app/code/Wyomind/SimpleGoogleShopping/Block/Adminhtml/Category
rm ./app/code/Wyomind/Core/view/adminhtml/web/js/codemirror/embedded.js
rm ./app/code/Wyomind/SimpleGoogleShopping/Helper/AttributesDefault.php
rmdir  ./app/code/Wyomind/Core/Block/Adminhtml/System/Config/Form/Field
rm ./app/code/Wyomind/SimpleGoogleShopping/Model/Config/UrlRewrite.php
rm ./app/code/Wyomind/Core/view/adminhtml/web/js/codemirror/css/css.js
rm ./app/code/Wyomind/Core/view/adminhtml/web/js/codemirror/xml/xml.js
rm ./app/code/Wyomind/Core/view/adminhtml/web/js/codemirror/php/php.js
rm ./app/code/Wyomind/SimpleGoogleShopping/Helper/AttributesImages.php
rm ./app/code/Wyomind/SimpleGoogleShopping/Console/Command/Listing.php
rm ./app/code/Wyomind/SimpleGoogleShopping/Helper/AttributesPrices.php
rmdir  ./app/code/Wyomind/SimpleGoogleShopping/view/adminhtml/web/css
rmdir  ./app/code/Wyomind/SimpleGoogleShopping/data/Google/Taxonomies
rmdir  ./app/code/Wyomind/Core/view/adminhtml/web/js/codemirror/clike
rm ./app/code/Wyomind/SimpleGoogleShopping/Block/Adminhtml/Feeds.php
rmdir  ./app/code/Wyomind/SimpleGoogleShopping/view/adminhtml/web/js
rmdir  ./app/code/Wyomind/SimpleGoogleShopping/Block/Adminhtml/Feeds
rmdir  ./app/code/Wyomind/SimpleGoogleShopping/view/adminhtml/layout
rmdir  ./app/code/Wyomind/Core/view/adminhtml/web/js/codemirror/php
rm ./app/code/Wyomind/Core/Observer/ControllerActionPredispatch.php
rmdir  ./app/code/Wyomind/Core/view/adminhtml/web/js/codemirror/css
rmdir  ./app/code/Wyomind/Core/view/adminhtml/web/js/codemirror/xml
rm ./app/code/Wyomind/Core/view/frontend/templates/webservice.phtml
rm ./app/code/Wyomind/SimpleGoogleShopping/Helper/AttributesUrl.php
rmdir  ./app/code/Wyomind/SimpleGoogleShopping/Controller/Adminhtml
rmdir  ./app/code/Wyomind/SimpleGoogleShopping/view/adminhtml/email
rm ./app/code/Wyomind/SimpleGoogleShopping/etc/adminhtml/system.xml
rm ./app/code/Wyomind/SimpleGoogleShopping/etc/adminhtml/routes.xml
rm ./app/code/Wyomind/SimpleGoogleShopping/Setup/UpgradeSchema.php
rmdir  ./app/code/Wyomind/SimpleGoogleShopping/Model/ResourceModel
rm ./app/code/Wyomind/SimpleGoogleShopping/etc/email_templates.xml
rm ./app/code/Wyomind/SimpleGoogleShopping/Helper/Requirements.php
rm ./app/code/Wyomind/SimpleGoogleShopping/Helper/CategoryTree.php
rm ./app/code/Wyomind/SimpleGoogleShopping/Setup/InstallSchema.php
rm ./app/code/Wyomind/SimpleGoogleShopping/etc/frontend/routes.xml
rmdir  ./app/code/Wyomind/Core/Block/Adminhtml/System/Config/Form
rmdir  ./app/code/Wyomind/SimpleGoogleShopping/view/adminhtml/web
rm ./app/code/Wyomind/SimpleGoogleShopping/Logger/HandlerCron.php
rm ./app/code/Wyomind/SimpleGoogleShopping/etc/adminhtml/menu.xml
rm ./app/code/Wyomind/SimpleGoogleShopping/Setup/InstallData.php
rm ./app/code/Wyomind/SimpleGoogleShopping/Setup/UpgradeData.php
rm ./app/code/Wyomind/SimpleGoogleShopping/Logger/LoggerCron.php
rm ./app/code/Wyomind/SimpleGoogleShopping/Helper/Attributes.php
rm ./app/code/Wyomind/SimpleGoogleShopping/Controller/Feeds.php
rmdir  ./app/code/Wyomind/Core/view/adminhtml/web/js/codemirror
rmdir  ./app/code/Wyomind/SimpleGoogleShopping/Controller/Feeds
rm ./app/code/Wyomind/Core/Controller/Activation/Webservice.php
rmdir  ./app/code/Wyomind/SimpleGoogleShopping/Block/Adminhtml
rm ./app/code/Wyomind/SimpleGoogleShopping/Model/Functions.php
rmdir  ./app/code/Wyomind/SimpleGoogleShopping/Console/Command
rm ./app/code/Wyomind/SimpleGoogleShopping/Model/Observer.php
rm ./app/code/Wyomind/SimpleGoogleShopping/Logger/Handler.php
rmdir  ./app/code/Wyomind/SimpleGoogleShopping/view/adminhtml
rm ./app/code/Wyomind/SimpleGoogleShopping/Logger/Logger.php
rm ./app/code/Wyomind/Core/view/adminhtml/web/css/system.css
rmdir  ./app/code/Wyomind/SimpleGoogleShopping/etc/adminhtml
rm ./app/code/Wyomind/SimpleGoogleShopping/Helper/Parser.php
rmdir  ./app/code/Wyomind/Core/Block/Adminhtml/System/Config
rm ./app/code/Wyomind/SimpleGoogleShopping/registration.php
rm ./app/code/Wyomind/Core/Model/ResourceModel/Schedule.php
rmdir  ./app/code/Wyomind/SimpleGoogleShopping/Model/Config
rmdir  ./app/code/Wyomind/SimpleGoogleShopping/etc/frontend
rm ./app/code/Wyomind/SimpleGoogleShopping/Helper/Data.php
rm ./app/code/Wyomind/SimpleGoogleShopping/Model/Feeds.php
rm ./app/code/Wyomind/SimpleGoogleShopping/etc/crontab.xml
rmdir  ./app/code/Wyomind/SimpleGoogleShopping/data/Google
rm ./app/code/Wyomind/SimpleGoogleShopping/etc/module.xml
rm ./app/code/Wyomind/SimpleGoogleShopping/etc/config.xml
rm ./app/code/Wyomind/SimpleGoogleShopping/i18n/en_US.csv
rm ./app/code/Wyomind/Core/Model/ResourceModel/Config.php
rm ./app/code/Wyomind/SimpleGoogleShopping/i18n/fr_FR.csv
rmdir  ./app/code/Wyomind/SimpleGoogleShopping/Controller
rm ./app/code/Wyomind/Core/Plugin/Config/Model/Config.php
rm ./app/code/Wyomind/SimpleGoogleShopping/composer.json
rm ./app/code/Wyomind/Core/Console/Command/Activate.php
rmdir  ./app/code/Wyomind/SimpleGoogleShopping/Console
rm ./app/code/Wyomind/SimpleGoogleShopping/LICENSE.TXT
rmdir  ./app/code/Wyomind/Core/view/frontend/templates
rm ./app/code/Wyomind/SimpleGoogleShopping/etc/acl.xml
rmdir  ./app/code/Wyomind/Core/view/adminhtml/web/css
rm ./app/code/Wyomind/SimpleGoogleShopping/etc/di.xml
rm ./app/code/Wyomind/Core/Console/Command/Status.php
rmdir  ./app/code/Wyomind/SimpleGoogleShopping/Helper
rmdir  ./app/code/Wyomind/SimpleGoogleShopping/Logger
rmdir  ./app/code/Wyomind/Core/Block/Adminhtml/System
rmdir  ./app/code/Wyomind/SimpleGoogleShopping/Setup
rmdir  ./app/code/Wyomind/SimpleGoogleShopping/Model
rmdir  ./app/code/Wyomind/Core/view/adminhtml/web/js
rmdir  ./app/code/Wyomind/SimpleGoogleShopping/Block
rmdir  ./app/code/Wyomind/Core/view/adminhtml/layout
rmdir  ./app/code/Wyomind/Core/Controller/Activation
rm ./app/code/Wyomind/Core/etc/adminhtml/system.xml
rmdir  ./app/code/Wyomind/SimpleGoogleShopping/i18n
rm ./app/code/Wyomind/Core/etc/adminhtml/events.xml
rmdir  ./app/code/Wyomind/SimpleGoogleShopping/view
rmdir  ./app/code/Wyomind/Core/view/frontend/layout
rmdir  ./app/code/Wyomind/SimpleGoogleShopping/data
rmdir  ./app/code/Wyomind/Core/Model/ResourceModel
rmdir  ./app/code/Wyomind/Core/Plugin/Config/Model
rm ./app/code/Wyomind/Core/etc/frontend/routes.xml
rm ./app/code/Wyomind/Core/Model/Notifications.php
rmdir  ./app/code/Wyomind/SimpleGoogleShopping/etc
rmdir  ./app/code/Wyomind/Core/view/adminhtml/web
rm ./app/code/Wyomind/Core/Block/Webservice.php
rm ./app/code/Wyomind/Core/etc/adminhtml/di.xml
rmdir  ./app/code/Wyomind/Core/Console/Command
rmdir  ./app/code/Wyomind/SimpleGoogleShopping
rmdir  ./app/code/Wyomind/Core/Block/Adminhtml
rmdir  ./app/code/Wyomind/Core/view/adminhtml
rm ./app/code/Wyomind/Core/Helper/License.php
rm ./app/code/Wyomind/Core/Logger/Handler.php
rmdir  ./app/code/Wyomind/Core/etc/adminhtml
rmdir  ./app/code/Wyomind/Core/view/frontend
rmdir  ./app/code/Wyomind/Core/Plugin/Config
rm ./app/code/Wyomind/Core/Logger/Logger.php
rm ./app/code/Wyomind/Core/registration.php
rmdir  ./app/code/Wyomind/Core/etc/frontend
rm ./app/code/Wyomind/Core/Helper/Data.php
rm ./app/code/Wyomind/Core/Helper/Core.php
rmdir  ./app/code/Wyomind/Core/Controller
rm ./app/code/Wyomind/Core/Model/Feed.php
rm ./app/code/Wyomind/Core/etc/config.xml
rm ./app/code/Wyomind/Core/etc/module.xml
rm ./app/code/Wyomind/Core/composer.json
rmdir  ./app/code/Wyomind/Core/Observer
rm ./app/code/Wyomind/Core/LICENSE.TXT
rmdir  ./app/code/Wyomind/Core/Console
rmdir  ./app/code/Wyomind/Core/Plugin
rm ./app/code/Wyomind/Core/etc/di.xml
rmdir  ./app/code/Wyomind/Core/Helper
rmdir  ./app/code/Wyomind/Core/Logger
rmdir  ./app/code/Wyomind/Core/Block
rmdir  ./app/code/Wyomind/Core/Model
rmdir  ./app/code/Wyomind/Core/view
rmdir  ./app/code/Wyomind/Core/etc
rmdir  ./app/code/Wyomind/Core
rmdir  ./app/code/Wyomind
rmdir  ./app/code
rmdir  ./app